### PR TITLE
Adds some read token endpoints

### PR DESCRIPTION
**Pull request by jules2689**
This adds delete_read_token and list_read_tokens to the gem along with the appropriate specs.

cc @capotej

### CODE REVIEW

**Comment by jules2689** [comment]
@capotej any chance of getting this looked at? 😄 

The CI run seems to have failed for an unrelated rubygems error, can we get a re-run on that? (I cant request one)

**Comment by capotej** [comment]
Sorry for the delay and thanks for the patch!

**Comment by jules2689** [comment]
No worries Thanks!

**Comment by capotej** [comment]
Just released to rubygems as 1.0.6

**Pull request merged**
