### PR TITLE
Only require JSON dependency for old Rubies that don't have it in stdlib

### PR DESCRIPTION
**Pull request by bdewater**

### CODE REVIEW

**Comment by bdewater** [comment]
The test failures (`Errno::ECONNREFUSED`) are not related to this change. The fact that the builds for Ruby 1.8.7 (needs external JSON 1.8 gem), 1.9.3 (JSON 1.8 in stdlib) and 2.4.3 (JSON 2.0 in stdlib) pass make me confident everything works as expected 🙂

**Comment by bdewater** [comment]
Is there anything I can do to help this get over the finish line @capotej ?

**Comment by capotej** [comment]
Hi, 

Thanks for submitting this patch. Can you tell me the motivation for replacing `multi_json`?  The library should be doing the same thing patch does internally: https://github.com/intridea/multi_json

**Comment by bdewater** [comment]
MultiJson is an extra dependency that doesn't add value here, since it ends up using the same JSON library anyway to do the actual parsing. Less is more :)

As described in https://www.mikeperham.com/2016/02/09/kill-your-dependencies/ it's simply not needed except for Ruby 1.8, which we can solve with a simple conditional statement.

**Comment by capotej** [comment]
I see, while that is a great post and we do usually try to limit our dependencies, we think that since this is a library, the cost of a single dependency is worth the value of it working in as many Ruby contexts as possible, such as JRuby, Rubinius, or other Rubies that don't have JSON compiled in for whatever reason. 

Closing, unless there is another argument for getting rid of this dependency.

**Comment by bdewater** [comment]
I was not aware this was a concern/goal, since there is no mention of it anywhere in the repo nor is it tested against on CI.

**Comment by capotej** [comment]
Good point, I'll add a note about this to our README. Thanks!

**Pull request closed without merging**
